api/urls.py
from django.contrib import admin
from django.urls import path, include

from rest_framework.documentation import include_docs_urls

app_name = 'api'
urlpatterns = [
    path('jet/', include('jet.urls', namespace='jet'), name='jet'),  # Django JET URLS
    path('admin/', admin.site.urls),
    path('manager/', include('manager.urls', namespace='manager'), name='manager'),
    path('request/', include('request.urls', namespace='request'), name='request'),
    path('vehicles/', include('vehicles.urls', namespace='vehicles'), name='vehicles'),
    path('companies/', include('companies.urls', namespace='companies'), name='companies'),
    path('users/', include('users.urls', namespace='users'), name='users'),
]

jet/urls.py
import django
from django.conf.urls import url

try:
    from django.views.i18n import JavaScriptCatalog
    javascript_catalog = JavaScriptCatalog.as_view()
except ImportError:  # Django < 2.0
    from django.views.i18n import javascript_catalog

from jet.views import add_bookmark_view, remove_bookmark_view, toggle_application_pin_view, model_lookup_view


app_name = 'jet'

urlpatterns = [
    url(
        r'^add_bookmark/$',
        add_bookmark_view,
        name='add_bookmark'
    ),
    url(
        r'^remove_bookmark/$',
        remove_bookmark_view,
        name='remove_bookmark'
    ),
    url(
        r'^toggle_application_pin/$',
        toggle_application_pin_view,
        name='toggle_application_pin'
    ),
    url(
        r'^model_lookup/$',
        model_lookup_view,
        name='model_lookup'
    ),
    url(
        r'^jsi18n/$',
        javascript_catalog,
        {'packages': 'django.contrib.admin+jet'},
        name='jsi18n'
    ),
]

if django.VERSION[:2] < (1, 8):
    from django.conf.urls import patterns
    urlpatterns = patterns('', *urlpatterns)

tulicencia/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('jet/', include('jet.urls', namespace='jet'), name='jet'),  # Django JET URLS
    path('jet/dashboard/', include('jet.dashboard.urls', namespace='jet-dashboard'), name='jet-dashboard'),
    path('reports/', include('reports.urls', namespace='reports'), name='reports'),
    path('api/', include('api.urls', namespace='api'), name='api'),
    path('payments/', include('payments.urls', namespace='payments'), name='payments'),
    path('', include('webclient.urls', namespace='webclient'), name='webclient'),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webclient/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

from . import views

app_name = 'webclient'
urlpatterns = [
    path('', views.Stepper.as_view(), name='stepper'),
    path('baucher/<int:pk>/request', views.BaucherView.as_view(), name='baucher-detail'),
    path('contact-form', views.ContactForm.as_view(), name='contact-form'),
    path('login', views.Login.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page="/"), name='logout'),
    path('forget-password/', views.ForgetPassword.as_view(), name='forget_password'),
    path('recover-password/', views.ResetPasswordView.as_view(), name='recover_password'),
    path('profile', views.Profile.as_view(), name='profile'),
    path('profile/<int:pk>/', views.ProfileDetail.as_view(), name='profile-detail'),
    path('request/<int:pk>/', views.RequestDetail.as_view(), name='request-detail'),
    path('terms', views.TermsView.as_view(), name='terms'),
    path('privacy', views.PrivacyPolicyView.as_view(), name='privacy'),
    path('transits/<int:state>', views.TransitList.as_view(), name='transit-list'),
]

webclient/models.py
from django.db import models

# Create your models here.

webclient/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from easy_pdf.views import PDFTemplateView

from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.utils.datastructures import MultiValueDictKeyError
from django.views.generic.base import TemplateView, View
from django.views.generic.detail import DetailView

from django_xhtml2pdf.utils import generate_pdf

from companies.models import TuLicencia, TransitDepartment, CeaRating, CrcRating, TransitRating
from manager.models import Police, State, City
from request.models import Request
from users.models import UserToken


class Stepper(TemplateView):
    """Vista para el stepper
    """

    template_name = 'webclient/stepper.html'


class BaucherView(PDFTemplateView):

    template_name = 'webclient/baucher.html'

    def get_context_data(self, **kwargs):
        request = Request.objects.get(pk=self.kwargs['pk'])
        tulicencia = TuLicencia.objects.filter(city=request.user.city).first()
        return super(BaucherView, self).get_context_data(
            pagesize='Letter',
            title='Baucher TuLicencia',
            request=request,
            tulicencia=tulicencia,
            **kwargs
        )


class ContactForm(TemplateView):
    """Vista para el stepper
    """

    template_name = 'webclient/contact_form.html'


class Login(TemplateView):
    """Vista para el login
    """

    template_name = 'webclient/login.html'


class Profile(LoginRequiredMixin, TemplateView):
    """Vista para el perfil
    """

    template_name = 'webclient/profile.html'
    login_url = '/login'
    redirect_field_name = 'redirect_to'

    def get_context_data(self, **kwargs):
        context = super(Profile, self).get_context_data(**kwargs)
        if self.request.user.user_type == 'EXU':
            requests = Request.objects.filter(user_request=self.request.user).order_by('request_date')
        else:
            requests = Request.objects.filter(user=self.request.user).order_by('request_date')
        context['requests'] = requests
        return context


class RequestDetail(LoginRequiredMixin, DetailView):
    """Detalle de una solicitud
    """

    model = Request
    template_name = 'webclient/request_detail.html'
    login_url = '/login'
    redirect_field_name = 'redirect_to'

    def get_context_data(self, **kwargs):
        print(self.request.user)
        context = super(RequestDetail, self).get_context_data(**kwargs)
        request_obj = Request.objects.get(pk=self.kwargs['pk'])
        user = request_obj.user
        cea_rt = False
        crc_rt = False
        transit_rt = False
        cea_rating = CeaRating.objects.filter(cea=request_obj.cea, user=user)
        crc_rating = CrcRating.objects.filter(crc=request_obj.crc, user=user)
        transit_rating = TransitRating.objects.filter(transit=request_obj.transit, user=user)
        if cea_rating.count() > 0:
            cea_rt = True
        if crc_rating.count() > 0:
            crc_rt = True
        if transit_rating.count() > 0:
            transit_rt = True
        context['cea_rating'] = cea_rt
        context['crc_rating'] = crc_rt
        context['transit_rating'] = transit_rt
        if self.request.user.user_type == 'EXU':
            context['express_user'] = self.request.user
        return context


class ProfileDetail(LoginRequiredMixin, DetailView):
    """Detalle de mi perfil
    """

    model = get_user_model()
    template_name='webclient/edit_profile.html'
    login_url = '/login'
    redirect_field_name = 'redirect_to'


class ForgetPassword(TemplateView):
    """Vista del olvidó la contraseña
    """

    template_name = 'webclient/forget_password.html'


class ResetPasswordView(TemplateView):
    """Vista para Recuperar la constraseña
    """

    template_name = 'webclient/recover_password.html'

    def post(self, request, *args, **kwargs):
        try:
            document_id = request.POST.get('document_id')
            password = request.POST.get('password')
            user = get_user_model().objects.filter(document_id=document_id).first()
            user.set_password(password)
            user.save()
            user_token = UserToken.objects.get(user=user)
            user_token.is_use_token = True
            user_token.save()

            messages.add_message(
                request,
                    messages.SUCCESS, 
                    "!Felicitaciones!, tu contraseña se ha cambiado correctamente, ahora puedes ingresar con tu nueva contraseña"
            )
            return HttpResponseRedirect(reverse('webclient:login'))

        except MultiValueDictKeyError:
            return HttpResponseRedirect(reverse('webclient:login'))		

    def get(self, request, *args, **kwargs):
        try:
            token = request.GET.get('token')
            try:
                user = UserToken.objects.get(is_use_token=False, password_activation_token=token)
            except UserToken.DoesNotExist:
                messages.add_message(
                    request,
                        messages.ERROR, 
                        "Lo sentimos el enlace al que intenta acceder ha dejado de funcionar"
                )
                return HttpResponseRedirect(reverse('webclient:forget_password'))

            context = self.get_context_data(user.user)
            return self.render_to_response(context)

        except MultiValueDictKeyError as e:
            print(e)
            return HttpResponseRedirect(reverse('webclient:login'))

        context = self.get_context_data()
        return self.render_to_response(context)

    def get_context_data(self,user=None, **kwargs):
        context = super(ResetPasswordView, self).get_context_data(**kwargs)
        context['user'] = user
        return context


class TermsView(TemplateView):
    template_name = 'webclient/policy_detail.html'

    def get_context_data(self, **kwargs):
        police = get_object_or_404(Police, police_type='TC')
        context = super(TermsView, self).get_context_data(**kwargs)
        context['name'] = police.get_police_type_display()
        context['content'] = police.text
        return context


class PrivacyPolicyView(TemplateView):
    template_name = 'webclient/policy_detail.html'

    def get_context_data(self, **kwargs):
        police = get_object_or_404(Police, police_type='PP')
        context = super(PrivacyPolicyView, self).get_context_data(**kwargs)
        context['name'] = police.get_police_type_display()
        context['content'] = police.text
        return context


class TransitList(TemplateView):
    """ Vista para ver los departamentos de tránsito cuando se da click
    al flujo de duplicado
    """

    template_name = 'webclient/TransitList.html'

    def get_context_data(self, **kwargs):
        state = State.objects.get(pk=self.kwargs['state'])
        cities = City.objects.alive().filter(state=state).order_by('name')
        transits = TransitDepartment.objects.filter(state=state)
        context = super(TransitList, self).get_context_data(**kwargs)
        context['transits'] = transits
        context['cities'] = cities
        context['state'] = state
        return context

webclient/templates/webclient/contact_form.html
{% extends 'webclient/base.html' %}

{% load static %}
{% load custom_range %}

{% block extra_css %}

    <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
    
{% endblock %}

{% block content %}

    <div class="col-12 form-box">

        <div class="limiter">
            <div class="container-login100">
                <div class="wrap-login100">
                    <div class="login100-pic js-tilt" data-tilt>
                        <img src="{% static 'images/img-contact.png' %}" alt="IMG">
                    </div>
    
                    <form class="login100-form validate-form" method="POST" id="contact-form">
                        {% csrf_token %}
                        <span class="login100-form-title">
                            Contacto
                        </span>
    
                        <div class="wrap-input100 validate-input" data-validate = "El nombre es requerido">
                            <input class="input100" type="text" name="full_name" id="full_name" placeholder="Nombre completo">
                            <span class="focus-input100"></span>
                        </div>

                        <div class="wrap-input100 validate-input" data-validate = "El correo es requerido: ejemplo@correo.com">
                            <input class="input100" type="email" name="email" id="email" placeholder="Correo electrónico">
                            <span class="focus-input100"></span>
                        </div>

                        <div class="wrap-input100 validate-input" data-validate = "Debes seleccionar un motivo">
                            <select class=" input100 form-control" type="select" id="contact_type" name="contact_type">
                                <option selected disabled value="">Seleccione un motivo</option>
                                <option value="PE">Petición</option>
                                <option value="QU">Queja</option>
                                <option value="PR">Pregunta</option>
                                <option value="RE">Reclamo</option>
                                <option value="SU">Sugerencia</option>
                                <option value="FE">Felicitaciones</option>
                            </select>
                            <span class="focus-input100"></span>
                        </div>

                        <div class="wrap-input100 validate-input" data-validate = "Debes ingresar un mensaje">
                            <textarea class="input100 form-control" type="textarea" id="message" name="message" rows="2" placeholder="Ingresa tu mensaje"></textarea>
                            <span class="focus-input100"></span>
                        </div>
                        
                        <div class="container-login100-form-btn">
                            <button class="login100-form-btn">
                                ENVIAR
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
   
{% endblock %}
{% block extra_js %}
    <script src="{% static 'js/tilt/tilt.jquery.min.js' %}"></script>
    <script>
        $('.js-tilt').tilt({
            scale: 1.1
        })
        
        function validateForm(){

            var input = $('.validate-input .input100');

            var check = true;

            for(var i=0; i<input.length +1; i++) {
                if(validate(input[i]) == false){
                    showValidate(input[i]);
                    check=false;
                }
            }

            return check;
        }


        $('.validate-form .input100').each(function(){
            $(this).focus(function(){
                hideValidate(this);
            });
        });

        function validate (input) {

            if($(input).attr('type') == 'email' || $(input).attr('name') == 'email') {
                if($(input).val().trim().match(/^([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{1,5}|[0-9]{1,3})(\]?)$/) == null) {
                    return false;
                }
            }
            else if($(input).attr('type') == 'text'){
                if($(input).val().trim() == ''){
                    return false;
                }
            }
            else if($(input).attr('type') == 'select'){
                if($('#contact_type option:selected').val() == ''){
                    return false;
                }
            }
            else if($(input).attr('type') == 'textarea'){
                if($(input).val().trim() == ''){
                    return false;
                }
            }
            else {
                if($(input).val() == ''){
                    return false;
                }
            }
        }

        function showValidate(input) {
            var thisAlert = $(input).parent();

            $(thisAlert).addClass('alert-validate');
        }

        function hideValidate(input) {
            var thisAlert = $(input).parent();

            $(thisAlert).removeClass('alert-validate');
        }

        $('#contact-form').on('submit', function(e){
            e.preventDefault()

            valid = validateForm();
            if (valid){
                data = {
                    'full_name': $('#full_name').val(),
                    'email': $('#email').val(),
                    'contact_type': $('#contact_type :selected').val(),
                    'message': $('#message').val()
                }
                axios.defaults.headers.common['X-CSRFToken'] = '{{csrf_token}}';
                axios.post('/api/manager/contact-form/', {
                    'full_name': $('#full_name').val(),
                    'email': $('#email').val(),
                    'contact_type': $('#contact_type :selected').val(),
                    'message': $('#message').val()
                })
                .then(function(response){
                    data = response.data
                    swal(
                        'Mensaje enviado',
                        'Tu mensaje ha sido enviado exitosamente. Gracias por contactarte con TuLicencia',
                        'success'
                    ).then((result) => {
                        if (result.value) {
                            location.reload()
                            }
                        })
                })
                .catch(function(error){
                    console.log(error)
                })
            }
        })

    </script>
{% endblock %}

webclient/templates/webclient/policy_detail.html
{% extends 'webclient/base.html' %}
{% load static %}{% load i18n %}

{% block title %}
        <title>TuLicencia, {{name}}</title>
{% endblock %}

{% block extra_css%}
    <link rel="stylesheet" href="{% static 'assets/css/polices.css' %}">
    <style>
        h2 {
            text-align: center;
            margin-bottom: 30px;
        }
    </style>
{% endblock %}


{% block content %}

  <br>
  <br>
  <main>
    <section class="terms">
      <div class="container text-justify terms-container">
        <div class="row align-items-center">
          <div class="col-12 police-title">
            <h2>{{name}}</h2>
          </div>
        </div>
        <div class="row">
          {{content}}
        </div>        
      </div>
    </section>
  </main>

{% endblock content %}

{% block scripts %}
{% endblock scripts %}

webclient/templates/webclient/profile.html
{% extends 'webclient/profile_base.html' %}

{% load static %}
{% load custom_range %}

{% block container %}
    <div class="row row-details">
        <div class="col-12">
            <span class="services-title">Mis Solicitudes</span>
            <table class="table_id display responsive no-wrap">
                <thead>
                    <tr>
                        <th scope="col"># Reserva</th>
                        <th scope="col">Fecha</th>
                        <th scope="col">Tramites</th>
                        <th scope="col">Estado</th>
                        <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                    {% for r in requests %}
                        <tr>
                            <th scope="row">{{r.booking}}</th>
                            <td>{{r.request_date}}</td>
                            <td>
                                <ul style="list-style-type: none;">
                                    {% for t in r.related_tramits.all %}
                                        <li>
                                            <li>{{t}}</li>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </td>
                            <td>{{r.get_request_status_display}}</td>
                            <td>
                                <a href="{% url 'webclient:request-detail' pk=r.pk %}">
                                    <i class="fas fa-eye" style="font-size: 1.5em"></i>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}
   
{% block js_extra %}
    <script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.18/r-2.2.2/datatables.min.js"></script>
    <script>
        var table = $('.table_id')
        table.DataTable({
            responsive: true,
            language: {
                "sProcessing":     "Procesando...",
                "sLengthMenu":     "Mostrar _MENU_ registros",
                "sZeroRecords":    "No se encontraron resultados",
                "sEmptyTable":     "Ningún dato disponible en esta tabla",
                "sInfo":           "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                "sInfoEmpty":      "Mostrando registros del 0 al 0 de un total de 0 registros",
                "sInfoFiltered":   "(filtrado de un total de _MAX_ registros)",
                "sInfoPostFix":    "",
                "sSearch":         "Buscar:",
                "sUrl":            "",
                "sInfoThousands":  ",",
                "sLoadingRecords": "Cargando...",
                "oPaginate": {
                    "sFirst":    "Primero",
                    "sLast":     "Último",
                    "sNext":     "Siguiente",
                    "sPrevious": "Anterior"
                },
                "oAria": {
                    "sSortAscending":  ": Activar para ordenar la columna de manera ascendente",
                    "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                }
            }
        });

    </script>
{% endblock %}

webclient/templates/webclient/recover_password.html
{% extends 'webclient/base.html' %}

{% load static %}
{% load custom_range %}

{% block extra_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
{% endblock %}

{% block content %}

    <div class="col-12 form-box">
        {% if messages  %}
            {% for message in messages %}
            <div class="alert alert-info">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                {{message}}
            </div>
            {% endfor %}
        {% endif %}
        <div class="limiter">
            <div class="container-login100">
                <div class="wrap-login100">
                    <div class="login100-pic js-tilt" data-tilt>
                        <img src="{% static 'images/img-forget.png' %}" alt="IMG">
                    </div>
    
                    <form method="POST" action="{% url 'webclient:recover_password' %}" id="reset_password" class="form-horizontal">
                        {% csrf_token %}
                        <span class="login100-form-title">
                            Crear nueva contraseña
                        </span>
                        <input type="hidden" name="document_id" value="{{user.document_id}}">
    
                        <div class="wrap-input100 validate-input" data-validate = "La nueva contraseña es requerida">
                            <input class="input100" type="password" name="password" placeholder="Nueva contraseña">
                            <span class="focus-input100"></span>
                        </div>

                        <div class="wrap-input100 validate-input" data-validate = "Debes ingresar de nuevo tu contraseña, o no coincide">
                            <input class="input100" type="password" name="password" placeholder="Repite tu nueva contraseña">
                            <span class="focus-input100"></span>
                        </div>
                        
                        <div class="container-login100-form-btn">
                            <button type="submit" class="login100-form-btn">
                                Cambiar Contraseña
                            </button>
                        </div>
    
                    </form>
                </div>
            </div>
        </div>

    </div>
   
{% endblock %}
{% block extra_js %}
    <script src="{% static 'js/tilt/tilt.jquery.min.js' %}"></script>
    <script>

        $('.js-tilt').tilt({
			scale: 1.1
		})
        
        function validateForm(){

            var input = $('.validate-input .input100');

            var check = true;

            for(var i=0; i<input.length; i++) {
                if(validate(input[i]) == false){
                    showValidate(input[i]);
                    check=false;
                }
            }

            return check;
        }


        $('.validate-form .input100').each(function(){
            $(this).focus(function(){
                hideValidate(this);
            });
        });

        function validate (input) {
            if($(input).attr('type') == 'email' || $(input).attr('name') == 'email') {
                if($(input).val().trim().match(/^([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{1,5}|[0-9]{1,3})(\]?)$/) == null) {
                    return false;
                }
            }
            else {
                if($(input).val().trim() == ''){
                    return false;
                }
            }
        }

        function showValidate(input) {
            var thisAlert = $(input).parent();

            $(thisAlert).addClass('alert-validate');
        }

        function hideValidate(input) {
            var thisAlert = $(input).parent();

            $(thisAlert).removeClass('alert-validate');
        }

    </script>
{% endblock %}

webclient/templates/webclient/scheleton.html
{% extends 'webclient/base.html' %}

{% load static %}
{% load custom_range %}

{% block extra_css %}
    
{% endblock %}

{% block content %}

    <div class="col-12 form-box">
        
    </div>
   
{% endblock %}
{% block extra_js %}
    <script>

    </script>
{% endblock %}