api/urls.py
from django.contrib import admin
from django.urls import path, include

from rest_framework.documentation import include_docs_urls

app_name = 'api'
urlpatterns = [
    path('jet/', include('jet.urls', namespace='jet'), name='jet'),  # Django JET URLS
    path('admin/', admin.site.urls),
    path('manager/', include('manager.urls', namespace='manager'), name='manager'),
    path('request/', include('request.urls', namespace='request'), name='request'),
    path('vehicles/', include('vehicles.urls', namespace='vehicles'), name='vehicles'),
    path('companies/', include('companies.urls', namespace='companies'), name='companies'),
    path('users/', include('users.urls', namespace='users'), name='users'),
]

jet/urls.py
import django
from django.conf.urls import url

try:
    from django.views.i18n import JavaScriptCatalog
    javascript_catalog = JavaScriptCatalog.as_view()
except ImportError:  # Django < 2.0
    from django.views.i18n import javascript_catalog

from jet.views import add_bookmark_view, remove_bookmark_view, toggle_application_pin_view, model_lookup_view


app_name = 'jet'

urlpatterns = [
    url(
        r'^add_bookmark/$',
        add_bookmark_view,
        name='add_bookmark'
    ),
    url(
        r'^remove_bookmark/$',
        remove_bookmark_view,
        name='remove_bookmark'
    ),
    url(
        r'^toggle_application_pin/$',
        toggle_application_pin_view,
        name='toggle_application_pin'
    ),
    url(
        r'^model_lookup/$',
        model_lookup_view,
        name='model_lookup'
    ),
    url(
        r'^jsi18n/$',
        javascript_catalog,
        {'packages': 'django.contrib.admin+jet'},
        name='jsi18n'
    ),
]

if django.VERSION[:2] < (1, 8):
    from django.conf.urls import patterns
    urlpatterns = patterns('', *urlpatterns)

manager/urls.py
from django.urls import path, include

from . import views

app_name = 'manager'
urlpatterns = [
    path('terms-and-conditions/', views.TermsAndConditions.as_view(), name='terms-and-conditions'),
    path('privacy-policies/', views.PrivacyPolicies.as_view(), name='privacy-policies'),
    path('states/', views.StateList.as_view(), name='states'),
    path('city/<int:stateId>/', views.CityList.as_view(), name='cities'),
    path('sector/<int:cityId>/', views.SectorList.as_view(), name='sectors'),
    path('contact-form/', views.ContactFormView.as_view(), name='contact-form'),
]

reports/urls.py
from django.urls import path, include

from . import views


app_name = 'reports'
urlpatterns = [
    path('', views.ReportView.as_view(), name="reports"),
    path('purchase/', views.Purchases.as_view(), name='purchases'),
    path('purchases/', views.PurchaseApi.as_view(), name='purchase-api'),
    path('credit/', views.Credits.as_view(), name='credits'),
    path('credits/', views.CreditsApi.as_view(), name='credit-api'),
    path('service/', views.ServicesByCompany.as_view(), name='services'),
    path('services-api/', views.ServicesByCompanyApi.as_view(), name='services-api'),
    path('cea/', views.CeaServices.as_view(), name='cea'),
    path('cea-api/', views.CeaServicesApi.as_view(), name='cea-api'),
    path('crc/', views.CrcServices.as_view(), name='crc'),
    path('crc-api/', views.CrcServicesApi.as_view(), name='crc-api'),
    
]

tulicencia/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('jet/', include('jet.urls', namespace='jet'), name='jet'),  # Django JET URLS
    path('jet/dashboard/', include('jet.dashboard.urls', namespace='jet-dashboard'), name='jet-dashboard'),
    path('reports/', include('reports.urls', namespace='reports'), name='reports'),
    path('api/', include('api.urls', namespace='api'), name='api'),
    path('payments/', include('payments.urls', namespace='payments'), name='payments'),
    path('', include('webclient.urls', namespace='webclient'), name='webclient'),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reports/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

reports/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import datetime
import json
import xlwt

from rest_framework import status
from rest_framework.response import Response
from rest_framework.views import APIView

from django.db.models import Avg, Count, Min, Sum, F, Q
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView

from jet.dashboard.modules import DashboardModule

from companies.models import Cea, Crc, TransitDepartment
from manager.models import State, City
from request.models import Request, RequestTramit
from request.serializers import RequestSerializer



class ReportView(TemplateView):
    template_name = 'reports/reports.html'

    def generate_xlsx_report(self, request, report):
        response = HttpResponse(content_type='text/csv')
        response['Content-Disposition'] = 'attachment; filename="reporte.xls"'
        
        wb = xlwt.Workbook(encoding='utf-8')
        row_num = 0
        font_style = xlwt.XFStyle()
        font_style.font.bold = True

        if report == "purchases":
            start_date = request['start']
            end_date = request['end']
            city = request['city']

            if city:
                requests = Request.objects.filter(
                    request_date__gte=start_date,
                    request_date__lte=end_date,
                    crc__city=city
                )
            
            else:
                requests = Request.objects.filter(
                    request_date__gte=start_date,
                    request_date__lte=end_date,
                )
            if(request['tramit']):
                requests = requests.filter(related_tramits__tramit_type=request['tramit'])

            records = requests.values_list(
                'user__first_name',
                'user__last_name',
                'user__document_id',
                'cea__name',
                'crc__name',
                'transit__name',
                'related_tramits__tramit_type',
                'request_date',
            )

            ws = wb.add_sheet(str('Compras'))

            columns = [
                'Nombres',
                'Apellidos',
                'Documento',
                'CEA',
                'CRC',
                'Organismo de transito',
                'tramites',
                'Fecha de Solicitud',
            ]

        elif report == "credits": 
            start_date = request['start']
            end_date = request['end']
            city = request['city']

            if city:
                requests = Request.objects.filter(
                    request_date__gte=start_date,
                    request_date__lte=end_date,
                    crc__city=city,
                    payment_type=Request.CREDITO
                )
            else:
                requests = Request.objects.filter(
                    request_date__gte=start_date,
                    request_date__lte=end_date,
                    payment_type=Request.CREDITO
                )

            if(request['tramit']):
                requests = requests.filter(related_tramits__tramit_type=request['tramit'])
            
            if(request['credit_status']):
                requests = requests.filter(credit_status=request['credit_status'])

            records = requests.values_list(
                'user__first_name',
                'user__last_name',
                'user__document_id',
                'booking',
                'cea__name',
                'crc__name',
                'transit__name',
                'related_tramits__tramit_type',
                'request_date',
                'credit_status'
            )

            ws = wb.add_sheet(str('Creditos'))

            columns = [
                'Nombres',
                'Apellidos',
                'Documento',
                'No Reserva',
                'CEA',
                'CRC',
                'Organismo de transito',
                'tramites',
                'Fecha de Solicitud',
                'Estado del credito'
            ]

        elif report == "companies": 
            start_date = request['start']
            end_date = request['end']
            state = request['state']
            cea = request['cea']
            crc = request['crc']
            transit = request['transit']

            query = []

            if state and state != '0':
                requests = Request.objects.filter(
                    request_date__gte=start_date,
                    request_date__lte=end_date,
                    state=state,
                )
            else:
                requests = Request.objects.filter(
                    request_date__gte=start_date,
                    request_date__lte=end_date,
                )

            if (request['request_status']):
                requests = requests.filter(request_status=request['request_status'])

            records = requests.values_list(
                'user__first_name',
                'user__last_name',
                'user__document_id',
                'booking',
                'cea__name',
                'crc__name',
                'transit__name',
                'related_tramits__tramit_type',
                'request_date',
                'credit_status'
            )

            ws = wb.add_sheet(str('Creditos'))

            columns = [
                'Nombres',
                'Apellidos',
                'Documento',
                'No Reserva',
                'CEA',
                'CRC',
                'Organismo de transito',
                'tramites',
                'Fecha de Solicitud',
                'Estado del credito'
            ]

        elif report == 'cea':
            start_date = request['start']
            end_date = request['end']
            cea = request.user.cea

            requests = Request.objects.filter(
                cea=cea,
                request_date__gte=start_date,
                request_date__lte=end_date,
                request_status=Request.PAID
            )

            if(request['cea_status']):
                requests = requests.filter(cea_status=request['cea_status'])

            records = requests.values_list(
                'user__first_name',
                'user__last_name',
                'user__document_id',
                'booking',
                'related_tramits__tramit_type',
                'request_date',
                'payment_type',
                'payment_date'
            )

            ws = wb.add_sheet(str('Servicios Cea'))

            columns = [
                'Nombres',
                'Apellidos',
                'Documento',
                'No Reserva',
                'Tramites',
                'Fecha de Solicitud',
                'Tipo de pago',
                'Fecha del pago'
            ]

        elif report == 'crc':
            start_date = request['start']
            end_date = request['end']
            crc = request.user.crc

            requests = Request.objects.filter(
                crc=crc,
                request_date__gte=start_date,
                request_date__lte=end_date,
                request_status=Request.PAID
            )

            if(request['crc_status']):
                requests = requests.filter(crc_status=request['crc_status'])

            records = requests.values_list(
                'user__first_name',
                'user__last_name',
                'user__document_id',
                'booking',
                'related_tramits__tramit_type',
                'request_date',
                'payment_type',
                'payment_date'
            )

            ws = wb.add_sheet(str('Servicios Cea'))

            columns = [
                'Nombres',
                'Apellidos',
                'Documento',
                'No Reserva',
                'Tramites',
                'Fecha de Solicitud',
                'Tipo de pago',
                'Fecha del pago'
            ]

        for col_num in range(len(columns)):
            ws.write(row_num, col_num, columns[col_num], font_style)

        font_style = xlwt.XFStyle()

        for row in records:
            row_num += 1
            for col_num in range(len(row)):
                ws.write(row_num, col_num, row[col_num], font_style)

        wb.save(response)

        return response

    @csrf_exempt
    def post(self, request, *args, **kwargs):
        report = request.POST['report']
        return self.generate_xlsx_report(request.POST, report)


class Purchases(TemplateView):
    """
    """

    template_name = 'reports/purchases.html'

    def get_context_data(self, **kwargs):
        context = super(Purchases, self).get_context_data(**kwargs)
        context['states'] = State.objects.alive().order_by('name')
        return context


class PurchaseApi(APIView):

    def post(self, request, format=None):
        try:
            start_date = request.data['start']
            end_date = request.data['end']
            city = request.data['city']

            if city:
                requests = Request.objects.filter(
                    request_date__gte=start_date,
                    request_date__lte=end_date,
                    crc__city=city
                )
            else:
                requests = Request.objects.filter(
                    request_date__gte=start_date,
                    request_date__lte=end_date,
                )
            if(request.data['tramit']):
                if request.data['tramit'] == 'LI':
                    requests = requests.filter(Q(related_tramits__tramit_type='PL') | Q(related_tramits__tramit_type='SL'))
                else:
                    requests = requests.filter(related_tramits__tramit_type=request.data['tramit'])
            

reports/templates/reports/cea_services.html
{% extends 'webclient/base.html' %}

{% load static %}
{% load humanize %}

{% block extra_css %}
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.10.18/datatables.min.css"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/jquery-ui.min.css' %}"/>
{% endblock %}

{% block nav %}
    <nav class="navbar navbar-expand-lg navbar-dark">
        <a class="navbar-brand" href="/">
            <img src="{% static 'images/logo.png' %}" width="100" height="60" alt="logo">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
            
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
            </ul>
            <div class="form-inline my-2 my-lg-0">
                <ul class="navbar-nav">
                    <li class="span6">
                        <div class="mycontent-left">
                            <a class="a-navbar" href="{% url 'webclient:contact-form' %}">Contacto</a> 
                        </div>
                    </li>
                </ul>

            </div>
        </div>
    </nav>
{% endblock %}

{% block content %}
    <div class="col-12 form-box">
        <div class="container-fluid mb-5" >
            <div class="row justify-content-left">
                <div class="col-12 mt-4 p-3" style="background-color: #fff;">
                    <h3 class="mt-2">Compras realizadas por los usuarios</h3>
                    <form class="purchases">
                        {% csrf_token %}

                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="dates" class="float-left">Fecha inicio</label>
                                <input type="text" class="input-sm form-control start-date" name="start" required autocomplete="off"/>
                            </div>
                            <div class="form-group col-md-6">
                                <label for="dates" class="float-left">Fecha de fin</label>
                                <input type="text" class="input-sm form-control end-date" name="end" required autocomplete="off"/>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="cea_status" class="float-left">Selecciona el estado</label>
                            <select class="form-control" id="cea_status" name="cea_status">
                                <option value="" selected disabled>Selecciona un estado</option>
                                <option value="NS">Sin Iniciar</option>
                                <option value="FN">Iniciado</option>
                                <option value="RC">Finalizado</option>
                            </select>
                        </div>
                        
                        <button type="submit" class="btn btn-primary float-right mb-4">Generar Reporte</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="table" hidden>
            <form action="/reports/" method="POST">
                {% csrf_token %}
                <input type="hidden" name="report" value="cea" />
                <input type="hidden" id="start-xls" name="start" value="" />
                <input type="hidden" id="end-xls" name="end" value="" />
                <input type="hidden" id="cea_status-xls" name="cea_status" value="" />
                <button type="submit" class="btn btn-export" >Exportar a Excel</button>
            </form>
            <table id="table_id" class="display">
                <thead class="thead">
                    <tr>
                        <th>Usuario</th>
                        <th>Documento</th>
                        <th>Número de reserva</th>
                        <th>Trámites</th>
                        <th>Fecha de Solicitud</th>
                        <th>Tipo de Pago</th>
                        <th>Fecha de pago</th>
                    </tr>
                </thead>
                <tbody class="tbody">
                    <tr>
                        <td>Row 1 Data 1</td>
                        <td>Row 1 Data 2</td>
                        <td>Row 1 Data 2</td>
                        <td>Row 1 Data 2</td>
                        <td>Row 1 Data 2</td>
                        <td>Row 1 Data 2</td>
                        <td>Row 1 Data 2</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    


{% endblock %}


{% block extra_js %}
    <script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.18/datatables.min.js"></script>
    <script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
    <script>

        $( ".start-date" ).datepicker({
            dateFormat: "yy-mm-dd"
        });

        $( ".end-date" ).datepicker({
            dateFormat: "yy-mm-dd"
        });

        $('.start-date').on('change', function(e){
            $('#start-xls').val($(this).val())
        })

        $('.end-date').on('change', function(e){
            $('#end-xls').val($(this).val())
        })

        $('#cea_status').on('change', function(e){
            $('#cea_status-xls').val($(this).val())
        })

        $('.purchases').on('submit', function(ev) {
            ev.preventDefault()
            var table = $('#table_id')
            if ($('.table').hasClass('full')){
                table.DataTable().destroy()
                $('.table').removeClass('full')
            }
            params = {
                'start': $('.start-date').val(),
                'end': $('.end-date').val(),
                'cea_status': $('#cea_status').val(),
            }
            axios.defaults.headers.common['X-CSRFToken'] = '{{csrf_token}}';
            axios.post('/reports/cea-api/', params)
            .then(function(response){
                data = response.data
                $('.tbody').empty()
                $.each(data, function( k, v ) {
                    var str = ''
                    if (v.related_tramits.length > 1){
                        str = `<li>${v.related_tramits[1]}</li>`
                    }
                   
                    $('.tbody').append(
                        `
                        <tr>
                            <td>${v.user.first_name} ${v.user.last_name}</td>
                            <td>${v.user.document_id}</td>
                            <td>${v.booking}</td>
                            <td>
                                <ul>
                                    <li>${v.related_tramits[0]}</li>
                                    ${str}
                                </ul>
                            </td>
                            <td>${v.request_date}</td>
                            <td>${v.payment_type}</td>
                            <td>${v.payment_date}</td>
                        </tr>
                        `
                    )
                });
                
               table.DataTable({
                    language: {
                        "sProcessing":     "Procesando...",
                        "sLengthMenu":     "Mostrar _MENU_ registros",
                        "sZeroRecords":    "No se encontraron resultados",
                        "sEmptyTable":     "Ningún dato disponible en esta tabla",
                        "sInfo":           "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                        "sInfoEmpty":      "Mostrando registros del 0 al 0 de un total de 0 registros",
                        "sInfoFiltered":   "(filtrado de un total de _MAX_ registros)",
                        "sInfoPostFix":    "",
                        "sSearch":         "Buscar:",
                        "sUrl":            "",
                        "sInfoThousands":  ",",
                        "sLoadingRecords": "Cargando...",
                        "oPaginate": {
                            "sFirst":    "Primero",
                            "sLast":     "Último",
                            "sNext":     "Siguiente",
                            "sPrevious": "Anterior"
                        },
                        "oAria": {
                            "sSortAscending":  ": Activar para ordenar la columna de manera ascendente",
                            "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                        }
                    }
                });
                $('.table').addClass('full')
                $('.table').removeAttr('hidden')

            })
            .catch(function (error) {
                console.log(error);
            })
        })
    </script>
{% endblock %}

reports/templates/reports/report_list.html
{% load i18n %}

<ul>
    <li class="contrast">
        <a href="/admin/reports/" title="Reportes">Reportes</a>
    </li>
        {% if request.user.is_superuser %}
            <li>
                <a href="{% url 'reports:purchases' %}" target="_blank">Compras realizadas</a>
            </li>
            <li>
                <a href="{% url 'reports:credits' %}" target="_blank">Solicitudes de Créditos</a>
            </li>
            <li>
                <a href="{% url 'reports:services' %}" target="_blank">Servicios adquiridos a cada proveedor</a>
            </li>
        {% elif request.user.user_type == 'CEA' %}
            <li>
                <a href="{% url 'reports:cea' %}" target="_blank">Servicios Adquiridos</a>
            </li>
        {% elif request.user.user_type == 'CRC' %}
            <li>
                <a href="{% url 'reports:crc' %}" target="_blank">Servicios Adquiridos</a>
            </li>
        {% endif %}
</ul>