api/urls.py
from django.contrib import admin
from django.urls import path, include

from rest_framework.documentation import include_docs_urls

app_name = 'api'
urlpatterns = [
    path('jet/', include('jet.urls', namespace='jet'), name='jet'),  # Django JET URLS
    path('admin/', admin.site.urls),
    path('manager/', include('manager.urls', namespace='manager'), name='manager'),
    path('request/', include('request.urls', namespace='request'), name='request'),
    path('vehicles/', include('vehicles.urls', namespace='vehicles'), name='vehicles'),
    path('companies/', include('companies.urls', namespace='companies'), name='companies'),
    path('users/', include('users.urls', namespace='users'), name='users'),
]

jet/dashboard/urls.py
import django
from django.conf.urls import url

try:
    from django.views.i18n import JavaScriptCatalog
    javascript_catalog = JavaScriptCatalog.as_view()
except ImportError:  # Django < 2.0
    from django.views.i18n import javascript_catalog

from jet.dashboard import dashboard
from jet.dashboard.views import update_dashboard_modules_view, add_user_dashboard_module_view, \
    update_dashboard_module_collapse_view, remove_dashboard_module_view, UpdateDashboardModuleView, \
    load_dashboard_module_view, reset_dashboard_view

app_name = 'dashboard'

urlpatterns = [
    url(
        r'^module/(?P<pk>\d+)/$',
        UpdateDashboardModuleView.as_view(),
        name='update_module'
    ),
    url(
        r'^update_dashboard_modules/$',
        update_dashboard_modules_view,
        name='update_dashboard_modules'
    ),
    url(
        r'^add_user_dashboard_module/$',
        add_user_dashboard_module_view,
        name='add_user_dashboard_module'
    ),
    url(
        r'^update_dashboard_module_collapse/$',
        update_dashboard_module_collapse_view,
        name='update_dashboard_module_collapse'
    ),
    url(
        r'^remove_dashboard_module/$',
        remove_dashboard_module_view,
        name='remove_dashboard_module'
    ),
    url(
        r'^load_dashboard_module/(?P<pk>\d+)/$',
        load_dashboard_module_view,
        name='load_dashboard_module'
    ),
    url(
        r'^reset_dashboard/$',
        reset_dashboard_view,
        name='reset_dashboard'
    ),
    url(
        r'^jsi18n/$',
        javascript_catalog,
        {'packages': 'jet'},
        name='jsi18n'
    ),
]

urlpatterns += dashboard.urls.get_urls()

if django.VERSION[:2] < (1, 8):
    from django.conf.urls import patterns
    urlpatterns = patterns('', *urlpatterns)

jet/urls.py
import django
from django.conf.urls import url

try:
    from django.views.i18n import JavaScriptCatalog
    javascript_catalog = JavaScriptCatalog.as_view()
except ImportError:  # Django < 2.0
    from django.views.i18n import javascript_catalog

from jet.views import add_bookmark_view, remove_bookmark_view, toggle_application_pin_view, model_lookup_view


app_name = 'jet'

urlpatterns = [
    url(
        r'^add_bookmark/$',
        add_bookmark_view,
        name='add_bookmark'
    ),
    url(
        r'^remove_bookmark/$',
        remove_bookmark_view,
        name='remove_bookmark'
    ),
    url(
        r'^toggle_application_pin/$',
        toggle_application_pin_view,
        name='toggle_application_pin'
    ),
    url(
        r'^model_lookup/$',
        model_lookup_view,
        name='model_lookup'
    ),
    url(
        r'^jsi18n/$',
        javascript_catalog,
        {'packages': 'django.contrib.admin+jet'},
        name='jsi18n'
    ),
]

if django.VERSION[:2] < (1, 8):
    from django.conf.urls import patterns
    urlpatterns = patterns('', *urlpatterns)

tulicencia/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('jet/', include('jet.urls', namespace='jet'), name='jet'),  # Django JET URLS
    path('jet/dashboard/', include('jet.dashboard.urls', namespace='jet-dashboard'), name='jet-dashboard'),
    path('reports/', include('reports.urls', namespace='reports'), name='reports'),
    path('api/', include('api.urls', namespace='api'), name='api'),
    path('payments/', include('payments.urls', namespace='payments'), name='payments'),
    path('', include('webclient.urls', namespace='webclient'), name='webclient'),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jet/dashboard/models.py
from importlib import import_module
import json
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _
from jet.utils import LazyDateTimeEncoder


@python_2_unicode_compatible
class UserDashboardModule(models.Model):
    title = models.CharField(verbose_name=_('Title'), max_length=255)
    module = models.CharField(verbose_name=_('module'), max_length=255)
    app_label = models.CharField(verbose_name=_('application name'), max_length=255, null=True, blank=True)
    user = models.PositiveIntegerField(verbose_name=_('user'))
    column = models.PositiveIntegerField(verbose_name=_('column'))
    order = models.IntegerField(verbose_name=_('order'))
    settings = models.TextField(verbose_name=_('settings'), default='', blank=True)
    children = models.TextField(verbose_name=_('children'), default='', blank=True)
    collapsed = models.BooleanField(verbose_name=_('collapsed'), default=False)

    class Meta:
        verbose_name = _('user dashboard module')
        verbose_name_plural = _('user dashboard modules')
        ordering = ('column', 'order')

    def __str__(self):
        return self.module

    def load_module(self):
        try:
            package, module_name = self.module.rsplit('.', 1)
            package = import_module(package)
            module = getattr(package, module_name)

            return module
        except AttributeError:
            return None
        except ImportError:
            return None

    def pop_settings(self, pop_settings):
        settings = json.loads(self.settings)

        for setting in pop_settings:
            if setting in settings:
                settings.pop(setting)

        self.settings = json.dumps(settings, cls=LazyDateTimeEncoder)
        self.save()

    def update_settings(self, update_settings):
        settings = json.loads(self.settings)

        settings.update(update_settings)

        self.settings = json.dumps(settings, cls=LazyDateTimeEncoder)
        self.save()

jet/dashboard/views.py
from django.contrib import messages
from django.core.exceptions import ValidationError
try:
    from django.core.urlresolvers import reverse
except ImportError: # Django 1.11
    from django.urls import reverse

from django.forms.formsets import formset_factory
from django.http import HttpResponseRedirect
from django.views.decorators.http import require_POST, require_GET
from jet.dashboard.forms import UpdateDashboardModulesForm, AddUserDashboardModuleForm, \
    UpdateDashboardModuleCollapseForm, RemoveDashboardModuleForm, ResetDashboardForm
from jet.dashboard.models import UserDashboardModule
from jet.utils import JsonResponse, get_app_list, SuccessMessageMixin, user_is_authenticated
from django.views.generic import UpdateView
from django.utils.translation import ugettext_lazy as _


class UpdateDashboardModuleView(SuccessMessageMixin, UpdateView):
    model = UserDashboardModule
    fields = ('title',)
    template_name = 'jet.dashboard/update_module.html'
    success_message = _('Widget was successfully updated')
    object = None
    module = None

    def has_permission(self, request):
        return request.user.is_active and request.user.is_staff

    def get_success_url(self):
        if self.object.app_label:
            return reverse('admin:app_list', kwargs={'app_label': self.object.app_label})
        else:
            return reverse('admin:index')

    def get_module(self):
        object = self.object if getattr(self, 'object', None) is not None else self.get_object()
        return object.load_module()

    def get_settings_form_kwargs(self):
        kwargs = {
            'initial': self.module.settings
        }

        if self.request.method in ('POST', 'PUT'):
            kwargs.update({
                'data': self.request.POST,
                'files': self.request.FILES,
            })
        return kwargs

    def get_settings_form(self):
        if self.module.settings_form:
            form = self.module.settings_form(**self.get_settings_form_kwargs())
            if hasattr(form, 'set_module'):
                form.set_module(self.module)
            return form

    def get_children_formset_kwargs(self):
        kwargs = {
            'initial': self.module.children,
            'prefix': 'children',
        }

        if self.request.method in ('POST', 'PUT'):
            kwargs.update({
                'data': self.request.POST,
                'files': self.request.FILES,
            })
        return kwargs

    def get_children_formset(self):
        if self.module.child_form:
            return formset_factory(self.module.child_form, can_delete=True, extra=1)(**self.get_children_formset_kwargs())

    def clean_children_data(self, children):
        children = list(filter(
            lambda item: isinstance(item, dict) and item and item.get('DELETE') is not True,
            children
        ))
        for item in children:
            item.pop('DELETE')
        return children

    def get_current_app(self):
        app_list = get_app_list({'request': self.request})

        for app in app_list:
            if app.get('app_label', app.get('name')) == self.object.app_label:
                return app

    def get_context_data(self, **kwargs):
        data = super(UpdateDashboardModuleView, self).get_context_data(**kwargs)
        data['title'] = _('Change')
        data['module'] = self.module
        data['settings_form'] = self.get_settings_form()
        data['children_formset'] = self.get_children_formset()
        data['child_name'] = self.module.child_name if self.module.child_name else _('Items')
        data['child_name_plural'] = self.module.child_name_plural if self.module.child_name_plural else _('Items')
        data['app'] = self.get_current_app()
        return data

    def dispatch(self, request, *args, **kwargs):
        if not self.has_permission(request):
            index_path = reverse('admin:index')
            return HttpResponseRedirect(index_path)

        self.object = self.get_object()
        self.module = self.get_module()(model=self.object)
        return super(UpdateDashboardModuleView, self).dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        settings_form = self.get_settings_form()
        children_formset = self.get_children_formset()

        data = request.POST.copy()

        if settings_form:
            if settings_form.is_valid():
                settings = settings_form.cleaned_data
                data['settings'] = self.module.dump_settings(settings)
            else:
                return self.form_invalid(self.get_form(self.get_form_class()))

        if children_formset:
            if children_formset.is_valid():
                self.module.children = self.clean_children_data(children_formset.cleaned_data)
                data['children'] = self.module.dump_children()
            else:
                return self.form_invalid(self.get_form(self.get_form_class()))

        request.POST = data

        return super(UpdateDashboardModuleView, self).post(request, *args, **kwargs)

    def form_valid(self, form):
        if 'settings' in form.data:
            form.instance.settings = form.data['settings']
        if 'children' in form.data:
            form.instance.children = form.data['children']
        return super(UpdateDashboardModuleView, self).form_valid(form)


@require_POST
def update_dashboard_modules_view(request):
    result = {'error': False}
    form = UpdateDashboardModulesForm(request, request.POST)

    if form.is_valid():
        form.save()
    else:
        result['error'] = True

    return JsonResponse(result)


@require_POST
def add_user_dashboard_module_view(request):
    result = {'error': False}
    form = AddUserDashboardModuleForm(request, request.POST)

    if form.is_valid():
        module = form.save()
        result['id'] = module.pk
        messages.success(request, _('Widget has been successfully added'))

        if module.app_label:
            result['success_url'] = reverse('admin:app_list', kwargs={'app_label': module.app_label})
        else:
            result['success_url'] = reverse('admin:index')
    else:
        result['error'] = True

    return JsonResponse(result)


@require_POST
def update_dashboard_module_collapse_view(request):
    result = {'error': False}

    try:
        instance = UserDashboardModule.objects.get(pk=request.POST.get('id'))
        form = UpdateDashboardModuleCollapseForm(request, request.POST, instance=instance)

        if form.is_valid():
            module = form.save()
            result['collapsed'] = module.collapsed
        else:
            result['error'] = True
    except UserDashboardModule.DoesNotExist:
        result['error'] = True

    return JsonResponse(result)


@require_POST
def remove_dashboard_module_view(request):
    result = {'error': False}

    try:
        instance = UserDashboardModule.objects.get(pk=request.POST.get('id'))
        form = RemoveDashboardModuleForm(request, request.POST, instance=instance)

        if form.is_valid():
            form.save()
        else:
            result['error'] = True
    except UserDashboardModule.DoesNotExist:
        result['error'] = True

    return JsonResponse(result)


@require_GET
def load_dashboard_module_view(request, pk):
    result = {'error': False}

    try:
        if not user_is_authenticated(request.user) or not request.user.is_staff:
            raise ValidationError('error')

        instance = UserDashboardModule.objects.get(pk=pk, user=request.user.pk)
        module_cls = instance.load_module()
        module = module_cls(model=instance, context={'request': request})
        result['html'] = module.render()
    except (ValidationError, UserDashboardModule.DoesNotExist):
        result['error'] = True

    return JsonResponse(result)


@require_POST
def reset_dashboard_view(request):
    result = {'error': False}
    form = ResetDashboardForm(request, request.POST)

    if form.is_valid():
        form.save()
    else:
        result['error'] = True

    return JsonResponse(result)

jet/dashboard/templates/jet.dashboard/dashboard.html
{% load i18n %}

<div class="dashboard-container columns_{{ columns|length }} cf">
    {% for i in columns %}
        <div class="dashboard-column-wrapper">
            <div class="dashboard-column{% if forloop.first %} first{% endif %}">
                {% for module in modules %}
                    {% if module.model.column == i %}
                        {% include "jet.dashboard/module.html" with module=module %}
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    {% endfor %}
</div>

<div class="dialog-confirm" id="module-remove-dialog" title="{% trans "Delete widget" %}">
    <p>{% trans "Are you sure want to delete this widget?" %}</p>
</div>

<form action="{% url "jet-dashboard:update_dashboard_modules" %}" method="POST" id="update-dashboard-modules-form">
    {% csrf_token %}
    <input type="hidden" name="app_label" value="{% if app_label %}{{ app_label }}{% endif %}">
    <input type="hidden" name="modules">
</form>

<form action="{% url "jet-dashboard:update_dashboard_module_collapse" %}" method="POST" id="update-dashboard-module-collapse-form">
    {% csrf_token %}
    <input type="hidden" name="id">
    <input type="hidden" name="collapsed">
</form>

<form action="{% url "jet-dashboard:remove_dashboard_module" %}" method="POST" id="remove-dashboard-module-form">
    {% csrf_token %}
    <input type="hidden" name="id">
</form>

jet/dashboard/templates/jet.dashboard/dashboard_tools.html
{% load i18n %}

<div class="dashboard-tools-toggle-container">
    <a href="#" class="dashboard-tools-toggle button">
        <span class="dashboard-tools-toggle-icon icon-settings"></span>
    </a>
</div>
<div class="dashboard-tools">
    <form action="{% url "jet-dashboard:add_user_dashboard_module" %}" method="POST" id="add-dashboard-module-form">
        {% csrf_token %}
        <select class="add-dashboard" name="module">
            <option>{% trans "widgets" %}</option>
            <optgroup label="{% trans "available" %}">
                {% for module in available_children %}
                    <option value="{{ forloop.counter0 }}" data-type="available_children">{{ module.title }}</option>
                {% endfor %}
            </optgroup>
            <optgroup label="{% trans "initials" %}">
                {% for module in children %}
                    <option value="{{ forloop.counter0 }}" data-type="children">{{ module.title }}</option>
                {% endfor %}
            </optgroup>
        </select><a href="#" class="button add-dashboard-link" title="{% trans "Add" %}"><span class="add-dashboard-link-icon icon-add"></span><span class="add-dashboard-link-label">{% trans "Add" %}</span></a>
        <input type="hidden" name="app_label" value="{% if app_label %}{{ app_label }}{% endif %}">
        <input type="hidden" name="type" value="">
        <a href="#" class="button transparent reset-dashboard-link" title="{% trans "Reset widgets" %}"><span class="reset-dashboard-link-icon icon-reset"></span><span class="reset-dashboard-link-label">{% trans "Reset widgets" %}</span></a>
    </form>
    <form action="{% url "jet-dashboard:reset_dashboard" %}" method="POST" id="reset-dashboard-form">
        {% csrf_token %}
        <input type="hidden" name="app_label" value="{% if app_label %}{{ app_label }}{% endif %}">
    </form>
    <div class="dialog-confirm" id="reset-dashboard-dialog" title="{% trans "Reset widgets" %}">
        <p>{% trans "Are you sure want to reset widgets?" %}</p>
    </div>
</div>

jet/dashboard/templates/jet.dashboard/module.html
{% load i18n %}

<div class="dashboard-item{% if module.collapsible %} collapsible{% endif %}{% if module.model.collapsed %} collapsed{% endif %}{% if module.deletable %} deletable{% endif %}{% if module.ajax_load %} ajax{% endif %}{% if module.draggable %} draggable{% endif %}"{% if module.ajax_load %} data-ajax-url="{% url "jet-dashboard:load_dashboard_module" pk=module.model.id %}"{% endif %} data-module-id="{{ module.model.id }}">
    <div class="dashboard-item-header">
        {% if module.draggable %}
            <span class="dashboard-item-header-drag icon-grid"></span>
        {% endif %}
        <span class="dashboard-item-header-buttons">
            <a href="{% url "jet-dashboard:update_module" pk=module.model.id %}" title="{% trans "Change" %}"><span class="icon-edit"></span></a>

            {% if module.deletable %}
                <a href="#" title="{% trans "Delete" %}" class="dashboard-item-remove"><span class="icon-cross"></span></a>
            {% endif %}
        </span>
        <span class="dashboard-item-header-title">
            {% if module.collapsible %}
                <a href="#" class="dashboard-item-collapse"><span class="dashboard-item-header-collapse-button icon-arrow-down"></span></a>
                <a href="#" class="dashboard-item-collapse"><span class="dashboard-item-header-collapse-button icon-arrow-up"></span></a>
            {% endif %}

            {% if module.title_url %}
                <a href="{{ module.title_url }}">{{ module.title }}</a>
            {% else %}
                {{ module.title }}
            {% endif %}
        </span>
        <div class="cf"></div>
    </div>

    <div class="dashboard-item-content{% if module.contrast %} contrast{% endif %}"{% if module.style %} style="{{ module.style }}"{% endif %}>
        {{ module.pre_contenta|default_if_none:"" }}
        {% if module.ajax_load %}
            <div class="loading-indicator-wrapper">
                <span class="icon-refresh loading-indicator"></span>
            </div>
        {% else %}
            {{ module.render }}
        {% endif %}
        {{ module.post_content|default_if_none:"" }}
    </div>
</div>

jet/dashboard/templates/jet.dashboard/update_module.html
{% extends "admin/base_site.html" %}
{% load i18n jet_tags static %}

{% if not is_popup %}
    {% block breadcrumbs %}
        <div class="breadcrumbs">
            <a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
            {% if app %}
                &rsaquo; <a href="{{ app.app_url }}">{% if app.name != app.app_label|capfirst|escape %}{{ app.name }}{% else %}{% trans app.app_label as app_label %}{{ app_label|capfirst|escape }}{% endif %}</a>
            {% endif %}
            &rsaquo; {{ object.title|capfirst }}
        </div>
    {% endblock %}
{% endif %}

{% block bodyclass %}{{ block.super }} dashboard jet change-form{% endblock %}

{% block content %}
    <div id="content-main">
        {% block object-tools %}{% endblock %}

        <form action="" method="post" novalidate>{% csrf_token %}{% block form_top %}{% endblock %}
            <div>
                {% if form.errors or settings_form.errors %}
                    <p class="errornote">{% trans "Please correct the errors below." %}</p>
                {% endif %}

                {% block field_sets %}
                    <fieldset class="module aligned">
                        {% include "jet.dashboard/update_module_fieldset.html" with form=form wrap=False %}

                        {% if settings_form %}
                            {% include "jet.dashboard/update_module_fieldset.html" with form=settings_form wrap=False %}
                        {% endif %}
                    </fieldset>
                {% endblock %}

                {% block after_field_sets %}{% endblock %}

                {% block inline_field_sets %}
                    {% if children_formset %}
                        <div class="inline-group">
                            <fieldset class="module">
                                <h2>{{ child_name_plural }}</h2>

                                {{ children_formset.management_form }}
                                {{ children_formset.non_form_errors }}

                                {% for form in children_formset %}
                                    <div class="inline-related{% if forloop.last %} empty-form last-related{% else %} has_original{% endif %}">
                                        <h3>
                                            <b>{{ child_name|capfirst }}:</b>&nbsp;<span class="inline_label">#{{ forloop.counter }}</span>

                                            {% if forloop.last %}
                                                <span><a href="#" class="inline-deletelink">{% trans "Delete" %}</a></span>
                                            {% elif children_formset.can_delete %}
                                                <span class="delete"><label>{{ form.DELETE }} {% trans "Delete" %}</label></span>
                                            {% endif %}
                                        </h3>

                                        {% if form.non_field_errors %}{{ form.non_field_errors }}{% endif %}

                                        {% include "jet.dashboard/update_module_fieldset.html" with form=form %}
                                    </div>
                                {% endfor %}

                                {% with child_name as verbose_name %}
                                    <div class="add-row">
                                        <a href="#">{% blocktrans %}Add another {{ verbose_name }}{% endblocktrans %}</a>
                                    </div>
                                {% endwith %}
                            </fieldset>
                        </div>
                    {% endif %}
                {% endblock %}

                {% block after_related_objects %}{% endblock %}

                {% block submit_buttons_bottom %}
                    <div class="submit-row">
                        <input type="submit" value="{% trans 'Save' %}" class="default" name="_save" />
                    </div>
                {% endblock %}

                {% block admin_change_form_document_ready %}{% endblock %}
            </div>
        </form>
    </div>
{% endblock %}

jet/dashboard/templates/jet.dashboard/update_module_fieldset.html
{% load i18n jet_tags %}

{% if wrap != False %}<fieldset class="module aligned">{% endif %}
    {% for field in form %}
        {% if field.name != 'DELETE' %}
            <div class="form-row{% if field.errors %} errors{% endif %}">
                {{ field.errors }}

                {% if field|jet_is_checkbox %}
                    {{ field }} <label{% if field.field.required %} class="required"{% endif %} for="{{ field.id_for_label }}">{{ field.label }}</label>
                {% else %}
                    <label{% if field.field.required %} class="required"{% endif %} for="{{ field.id_for_label }}">{{ field.label }}:</label>
                    {{ field }}
                {% endif %}

                {% if field.field.help_text %}
                    <p class="help">{{ field.field.help_text|safe }}</p>
                {% endif %}
            </div>
        {% endif %}
    {% endfor %}
{% if wrap != False %}</fieldset>{% endif %}