api/urls.py
from django.contrib import admin
from django.urls import path, include

from rest_framework.documentation import include_docs_urls

app_name = 'api'
urlpatterns = [
    path('jet/', include('jet.urls', namespace='jet'), name='jet'),  # Django JET URLS
    path('admin/', admin.site.urls),
    path('manager/', include('manager.urls', namespace='manager'), name='manager'),
    path('request/', include('request.urls', namespace='request'), name='request'),
    path('vehicles/', include('vehicles.urls', namespace='vehicles'), name='vehicles'),
    path('companies/', include('companies.urls', namespace='companies'), name='companies'),
    path('users/', include('users.urls', namespace='users'), name='users'),
]

jet/urls.py
import django
from django.conf.urls import url

try:
    from django.views.i18n import JavaScriptCatalog
    javascript_catalog = JavaScriptCatalog.as_view()
except ImportError:  # Django < 2.0
    from django.views.i18n import javascript_catalog

from jet.views import add_bookmark_view, remove_bookmark_view, toggle_application_pin_view, model_lookup_view


app_name = 'jet'

urlpatterns = [
    url(
        r'^add_bookmark/$',
        add_bookmark_view,
        name='add_bookmark'
    ),
    url(
        r'^remove_bookmark/$',
        remove_bookmark_view,
        name='remove_bookmark'
    ),
    url(
        r'^toggle_application_pin/$',
        toggle_application_pin_view,
        name='toggle_application_pin'
    ),
    url(
        r'^model_lookup/$',
        model_lookup_view,
        name='model_lookup'
    ),
    url(
        r'^jsi18n/$',
        javascript_catalog,
        {'packages': 'django.contrib.admin+jet'},
        name='jsi18n'
    ),
]

if django.VERSION[:2] < (1, 8):
    from django.conf.urls import patterns
    urlpatterns = patterns('', *urlpatterns)

tulicencia/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('jet/', include('jet.urls', namespace='jet'), name='jet'),  # Django JET URLS
    path('jet/dashboard/', include('jet.dashboard.urls', namespace='jet-dashboard'), name='jet-dashboard'),
    path('reports/', include('reports.urls', namespace='reports'), name='reports'),
    path('api/', include('api.urls', namespace='api'), name='api'),
    path('payments/', include('payments.urls', namespace='payments'), name='payments'),
    path('', include('webclient.urls', namespace='webclient'), name='webclient'),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webclient/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

from . import views

app_name = 'webclient'
urlpatterns = [
    path('', views.Stepper.as_view(), name='stepper'),
    path('baucher/<int:pk>/request', views.BaucherView.as_view(), name='baucher-detail'),
    path('contact-form', views.ContactForm.as_view(), name='contact-form'),
    path('login', views.Login.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page="/"), name='logout'),
    path('forget-password/', views.ForgetPassword.as_view(), name='forget_password'),
    path('recover-password/', views.ResetPasswordView.as_view(), name='recover_password'),
    path('profile', views.Profile.as_view(), name='profile'),
    path('profile/<int:pk>/', views.ProfileDetail.as_view(), name='profile-detail'),
    path('request/<int:pk>/', views.RequestDetail.as_view(), name='request-detail'),
    path('terms', views.TermsView.as_view(), name='terms'),
    path('privacy', views.PrivacyPolicyView.as_view(), name='privacy'),
    path('transits/<int:state>', views.TransitList.as_view(), name='transit-list'),
]

webclient/models.py
from django.db import models

# Create your models here.

webclient/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from easy_pdf.views import PDFTemplateView

from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.utils.datastructures import MultiValueDictKeyError
from django.views.generic.base import TemplateView, View
from django.views.generic.detail import DetailView

from django_xhtml2pdf.utils import generate_pdf

from companies.models import TuLicencia, TransitDepartment, CeaRating, CrcRating, TransitRating
from manager.models import Police, State, City
from request.models import Request
from users.models import UserToken


class Stepper(TemplateView):
    """Vista para el stepper
    """

    template_name = 'webclient/stepper.html'


class BaucherView(PDFTemplateView):

    template_name = 'webclient/baucher.html'

    def get_context_data(self, **kwargs):
        request = Request.objects.get(pk=self.kwargs['pk'])
        tulicencia = TuLicencia.objects.filter(city=request.user.city).first()
        return super(BaucherView, self).get_context_data(
            pagesize='Letter',
            title='Baucher TuLicencia',
            request=request,
            tulicencia=tulicencia,
            **kwargs
        )


class ContactForm(TemplateView):
    """Vista para el stepper
    """

    template_name = 'webclient/contact_form.html'


class Login(TemplateView):
    """Vista para el login
    """

    template_name = 'webclient/login.html'


class Profile(LoginRequiredMixin, TemplateView):
    """Vista para el perfil
    """

    template_name = 'webclient/profile.html'
    login_url = '/login'
    redirect_field_name = 'redirect_to'

    def get_context_data(self, **kwargs):
        context = super(Profile, self).get_context_data(**kwargs)
        if self.request.user.user_type == 'EXU':
            requests = Request.objects.filter(user_request=self.request.user).order_by('request_date')
        else:
            requests = Request.objects.filter(user=self.request.user).order_by('request_date')
        context['requests'] = requests
        return context


class RequestDetail(LoginRequiredMixin, DetailView):
    """Detalle de una solicitud
    """

    model = Request
    template_name = 'webclient/request_detail.html'
    login_url = '/login'
    redirect_field_name = 'redirect_to'

    def get_context_data(self, **kwargs):
        print(self.request.user)
        context = super(RequestDetail, self).get_context_data(**kwargs)
        request_obj = Request.objects.get(pk=self.kwargs['pk'])
        user = request_obj.user
        cea_rt = False
        crc_rt = False
        transit_rt = False
        cea_rating = CeaRating.objects.filter(cea=request_obj.cea, user=user)
        crc_rating = CrcRating.objects.filter(crc=request_obj.crc, user=user)
        transit_rating = TransitRating.objects.filter(transit=request_obj.transit, user=user)
        if cea_rating.count() > 0:
            cea_rt = True
        if crc_rating.count() > 0:
            crc_rt = True
        if transit_rating.count() > 0:
            transit_rt = True
        context['cea_rating'] = cea_rt
        context['crc_rating'] = crc_rt
        context['transit_rating'] = transit_rt
        if self.request.user.user_type == 'EXU':
            context['express_user'] = self.request.user
        return context


class ProfileDetail(LoginRequiredMixin, DetailView):
    """Detalle de mi perfil
    """

    model = get_user_model()
    template_name='webclient/edit_profile.html'
    login_url = '/login'
    redirect_field_name = 'redirect_to'


class ForgetPassword(TemplateView):
    """Vista del olvidó la contraseña
    """

    template_name = 'webclient/forget_password.html'


class ResetPasswordView(TemplateView):
    """Vista para Recuperar la constraseña
    """

    template_name = 'webclient/recover_password.html'

    def post(self, request, *args, **kwargs):
        try:
            document_id = request.POST.get('document_id')
            password = request.POST.get('password')
            user = get_user_model().objects.filter(document_id=document_id).first()
            user.set_password(password)
            user.save()
            user_token = UserToken.objects.get(user=user)
            user_token.is_use_token = True
            user_token.save()

            messages.add_message(
                request,
                    messages.SUCCESS, 
                    "!Felicitaciones!, tu contraseña se ha cambiado correctamente, ahora puedes ingresar con tu nueva contraseña"
            )
            return HttpResponseRedirect(reverse('webclient:login'))

        except MultiValueDictKeyError:
            return HttpResponseRedirect(reverse('webclient:login'))		

    def get(self, request, *args, **kwargs):
        try:
            token = request.GET.get('token')
            try:
                user = UserToken.objects.get(is_use_token=False, password_activation_token=token)
            except UserToken.DoesNotExist:
                messages.add_message(
                    request,
                        messages.ERROR, 
                        "Lo sentimos el enlace al que intenta acceder ha dejado de funcionar"
                )
                return HttpResponseRedirect(reverse('webclient:forget_password'))

            context = self.get_context_data(user.user)
            return self.render_to_response(context)

        except MultiValueDictKeyError as e:
            print(e)
            return HttpResponseRedirect(reverse('webclient:login'))

        context = self.get_context_data()
        return self.render_to_response(context)

    def get_context_data(self,user=None, **kwargs):
        context = super(ResetPasswordView, self).get_context_data(**kwargs)
        context['user'] = user
        return context


class TermsView(TemplateView):
    template_name = 'webclient/policy_detail.html'

    def get_context_data(self, **kwargs):
        police = get_object_or_404(Police, police_type='TC')
        context = super(TermsView, self).get_context_data(**kwargs)
        context['name'] = police.get_police_type_display()
        context['content'] = police.text
        return context


class PrivacyPolicyView(TemplateView):
    template_name = 'webclient/policy_detail.html'

    def get_context_data(self, **kwargs):
        police = get_object_or_404(Police, police_type='PP')
        context = super(PrivacyPolicyView, self).get_context_data(**kwargs)
        context['name'] = police.get_police_type_display()
        context['content'] = police.text
        return context


class TransitList(TemplateView):
    """ Vista para ver los departamentos de tránsito cuando se da click
    al flujo de duplicado
    """

    template_name = 'webclient/TransitList.html'

    def get_context_data(self, **kwargs):
        state = State.objects.get(pk=self.kwargs['state'])
        cities = City.objects.alive().filter(state=state).order_by('name')
        transits = TransitDepartment.objects.filter(state=state)
        context = super(TransitList, self).get_context_data(**kwargs)
        context['transits'] = transits
        context['cities'] = cities
        context['state'] = state
        return context

tulicencia/templates/webclient/base.html
{% load static %}
{% load custom_range %}

<!DOCTYPE html>
<html lang="es">

    <head>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no">
        {% block title %}
            <title>TuLicencia</title>
        {% endblock %}

        <!-- CSS -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:400,100,300,500">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
        <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">
        <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900" rel="stylesheet">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.0/animate.min.css">
        <link rel="stylesheet" href="{% static 'assets/font-awesome/css/font-awesome.css' %}">
		<link rel="stylesheet" href="{% static 'assets/css/form-elements.css' %}">
        <!-- <link rel="stylesheet" href="{% static 'assets/css/style.css' %}"> -->
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
        <link rel="stylesheet" href="{% static 'css/util.css' %}">

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!-- [if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif] -->

        <!-- Favicon and touch icons -->
        <link rel="shortcut icon" href="{% static 'icons/tl.ico' %}">
        <script src='https://www.google.com/recaptcha/api.js'></script>
        {% block extra_css %}
        {% endblock %}
    </head>

    <body>

        <!-- Top menu -->
        {% block nav %}
        <nav class="navbar navbar-expand-lg navbar-dark">
            <a class="navbar-brand" href="/">
                <img src="{% static 'images/logo.png' %}" width="70" height="40" alt="logo">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
                <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                </ul>
                <form class="form-inline my-2 my-lg-0">
                    <a class="pr-4 a-navbar " href="{% url 'webclient:contact-form' %}">Contacto</a>
                    {% if request.user.is_authenticated %}
                        <div class="dropdown show">
                            <a class="a-navbar dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                {{request.user.email}}
                                <img class="img-profile" src="{% static 'images/12.png' %}" width="25" height="25" alt="logo">
                            </a>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                <a class="dropdown-item" href="{% url 'webclient:profile' %}">Mi Perfil</a>
                                <a class="dropdown-item" href="{% url 'webclient:logout' %}">Cerrar Sesión</a>
                            </div>
                        </div>
                    {% else %}
                        <a class="pl-4 pr-4 border-left a-navbar" href="{% url 'webclient:login' %}">
                            Iniciar Sesion
                            <img class="ml-4 img-profile" src="{% static 'images/login.png' %}" width="25" height="25" alt="logo">
                        </a>
                    {% endif %}
                </form>
            </div>
        </nav>
        {% endblock %}

        <!-- Top content -->
        <div class="top-content">
            <div class="container-fluid">
                <!-- <div class="row justify-content-center"> -->
                    {% block content %}

                    {% endblock %}
                <!-- </div> -->
            </div>
        </div>


        <!-- Javascript -->
        <!-- <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script> -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/sweetalert2@7.28.4/dist/sweetalert2.all.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
        <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
        <script src="{% static 'assets/js/jquery.backstretch.min.js' %}"></script>
        <script src="{% static 'assets/js/scripts.js' %}"></script>

        <script>
            axios.defaults.headers.common['Api-Key'] = 'f89da732ed851a18d2eb64e1ebcdee913ee12487';
        </script>
        {% block extra_js %}
        {% endblock %}
    </body>

</html>

tulicencia/templates/webclient/profile_base.html
{% extends 'webclient/base.html' %}

{% load static %}
{% load custom_range %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/profile.css' %}">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.10.18/r-2.2.2/datatables.min.css"/>
    
{% endblock %}

{% block nav %}
    <nav class="navbar navbar-expand-lg navbar-dark">
        <a class="navbar-brand" href="/">
            <img src="{% static 'images/logo.png' %}" width="100" height="60" alt="logo">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
            
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
            </ul>
            <div class="form-inline my-2 my-lg-0">
                <ul class="navbar-nav">
                    <li class="span6">
                        <div class="mycontent-left">
                            <a class="a-navbar" href="{% url 'webclient:contact-form' %}">Contacto</a> 
                        </div>
                    </li>
                    <li class="span6">
                        <div class="mycontent-right">
                                <div class="dropdown show">
                                    <a class="a-navbar dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        {{request.user.email}}
                                        <img class="img-profile" src="{% static 'images/12.png' %}" width="25" height="25" alt="logo">
                                    </a>
                                    
                                    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                        <a class="dropdown-item" href="{% url 'webclient:profile' %}">Mi Perfil</a>
                                        <a class="dropdown-item" href="{% url 'webclient:logout' %}">Cerrar Sesión</a>
                                    </div>
                                </div>
                                
                        </div>
                    </li>
                </ul>

            </div>
        </div>
    </nav>
{% endblock %}

{% block content %}

    <div class="col-12 form-box">
        <div class="container-fluid">
            <div class="row profile-title">
                <div class="col-12">
                   <span>
                        Mi Perfil
                   </span>
                </div>
            </div>
            <div class="row profile-info align-items-center">
                <div class="col-12">
                    <div class="row profile-description">
                        <div class="col-md-3 col-lg-2 align-self-center">
                            <img class="img-profile-1" src="{% static 'images/07.png' %}" alt="user-img" width="100" height="100">
                        </div>
                        <div class="col-md-5 col-lg-6 align-self-center">
                            <span class="description-email">
                                {{request.user.email}}  
                                <i class="fas fa-check-circle"></i>
                            </span>
                        </div>
                        <div class="col-md-3 col-lg-3 align-self-center">
                            <a href="{% url 'webclient:profile-detail' pk=request.user.pk %}" class="btn btn-edit">Editar</a>
                        </div>
                    </div>
                    <div class="row profile-detail align-items-center">
                        <div class="col-md-6 col-lg-3">
                            <div class="row">
                                <div class="col-3 align-self-center">
                                    <img src="{% static 'images/08.png' %}" alt="" width="50" height="50">
                                </div>
                                <div class="col-8 align-self-center">
                                    <span class="detail-title">Datos personales</span>
                                    <span class="detail-info">{{request.user.get_full_name}}</span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-lg-3 align-self-center">
                            <div class="row">
                                <div class="col-3 align-self-center">
                                    <img src="{% static 'images/10.png' %}" alt="" width="50" height="50">
                                </div>
                                <div class="col-8 align-self-center">
                                    <span class="detail-title">Correo electrónico</span>
                                    <span class="detail-info">{{request.user.email}}</span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-lg-3 align-self-center">
                            <div class="row">
                                <div class="col-3 col-lg-5 align-self-center">
                                    <img src="{% static 'images/09.png' %}" alt="" width="50" height="50">
                                </div>
                                <div class="col-8 col-lg-7 align-self-center">
                                    <span class="detail-title">Teléfono</span>
                                    <span class="detail-info">{{request.user.cellphone|default:"Sin telefono"}}</span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-lg-3 align-self-center">
                            <div class="row">
                                <div class="col-3 col-lg-5 align-self-center">
                                    <img src="{% static 'images/11.png' %}" alt="" width="50" height="50">
                                </div>
                                <div class="col-8 col-lg-7 align-self-center">
                                    <span class="detail-title">Contraseña</span>
                                    <span class="detail-info">************</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% block container %}
                <div class="row row-details">
                    <div class="col-12">
                        <span class="services-title">Mis Solicitudes</span>
                        <table class="table_id">
                            <thead>
                                <tr>
                                    <th scope="col"># Reserva</th>
                                    <th scope="col">Fecha</th>
                                    <th scope="col">Tramites</th>
                                    <th scope="col">Estado</th>
                                    <th scope="col"></th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for r in requests %}
                                    <tr>
                                        <th scope="row">{{r.booking}}</th>
                                        <td>{{r.request_date}}</td>
                                        <td>
                                            <ul style="list-style-type: none;">
                                                {% for t in r.related_tramits.all %}
                                                    <li>
                                                        <li>{{t}}</li>
                                                    </li>
                                                {% endfor %}
                                            </ul>
                                        </td>
                                        <td>{{r.get_request_status_display}}</td>
                                        <td>
                                            <a href="{% url 'webclient:request-detail' pk=r.pk %}">
                                                <i class="fas fa-eye" style="font-size: 1.5em"></i>
                                            </a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            {% endblock %}
        </div>
    </div>
   
{% endblock %}
{% block extra_js %}
    {% block js_extra %}
        <script>
            axios.defaults.headers.common['Api-Key'] = 'f89da732ed851a18d2eb64e1ebcdee913ee12487';
        </script>
    {% endblock %}
{% endblock %}